//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GerenciadorTarefas.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBDTECEntities1 : DbContext
    {
        public DBDTECEntities1()
            : base("name=DBDTECEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Prioridade> Prioridade { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Tarefa> Tarefa { get; set; }
        public virtual DbSet<TipoTarefa> TipoTarefa { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
    
        public virtual int UP_TOI_APAGAR_CALCULOS_REPETIDOS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UP_TOI_APAGAR_CALCULOS_REPETIDOS");
        }
    
        public virtual int UP_TOI_EXPORT_001(string tIPO_TOI)
        {
            var tIPO_TOIParameter = tIPO_TOI != null ?
                new ObjectParameter("TIPO_TOI", tIPO_TOI) :
                new ObjectParameter("TIPO_TOI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UP_TOI_EXPORT_001", tIPO_TOIParameter);
        }
    
        public virtual int UP_TOI_ImpCalculado_TO_Calculo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UP_TOI_ImpCalculado_TO_Calculo");
        }
    
        public virtual int UP_TOI_ImpEncerramento_To_Toi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UP_TOI_ImpEncerramento_To_Toi");
        }
    
        public virtual int UP_TOI_ImpFaturados_To_ToiFaturamento()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UP_TOI_ImpFaturados_To_ToiFaturamento");
        }
    
        public virtual int UP_TOI_ImpGerado_TO_Toi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UP_TOI_ImpGerado_TO_Toi");
        }
    
        public virtual int UP_TOI_Indicador_TOI_CRIADOS_POR_STATUS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UP_TOI_Indicador_TOI_CRIADOS_POR_STATUS");
        }
    
        public virtual int UP_TOI_Indicador_TOI_POR_STATUS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UP_TOI_Indicador_TOI_POR_STATUS");
        }
    }
}
