//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GerenciadorTarefas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarefa
    {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Descricao { get; set; }
        public System.DateTime DataCriacao { get; set; }
        public Nullable<System.DateTime> DataTermino { get; set; }
        public int StatusId { get; set; }
        public int PrioridadeId { get; set; }
        public int UsuarioId { get; set; }
        public int TipoTarefaId { get; set; }
    
        public virtual Prioridade Prioridade { get; set; }
        public virtual Status Status { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual TipoTarefa TipoTarefa { get; set; }
    }
}
